name: gh-pages-deploy-mkdocs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r ./requirements.txt
      - run: pip install ghp-import
      - run: mkdocs build
      - run: ghp-import site -p -x site